//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Systems/Input/VoxelEditorInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VoxelEditorInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VoxelEditorInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""VoxelEditorInput"",
    ""maps"": [
        {
            ""name"": ""Editor"",
            ""id"": ""39885907-c59b-4e8e-b2f7-a7f13af2df71"",
            ""actions"": [
                {
                    ""name"": ""CameraPan"",
                    ""type"": ""Value"",
                    ""id"": ""040eafd8-6076-473a-bec3-9f02e45062d2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraRotate"",
                    ""type"": ""Value"",
                    ""id"": ""73b75e47-0d9a-4b23-b605-d20d46a5641a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraZoom"",
                    ""type"": ""Value"",
                    ""id"": ""92bebe5b-8bea-4e05-8b09-ddb31aba314e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlaceBlock"",
                    ""type"": ""Button"",
                    ""id"": ""915b2316-8094-4561-8b23-3a226a0e2a81"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RemoveBlock"",
                    ""type"": ""Button"",
                    ""id"": ""bc3a2dee-b657-492d-b5f0-235bf629eab8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""70cb985d-4dfc-4c54-bfc7-e5f640ab7f52"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraPan"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""78f09381-49ce-49ca-9628-2d4fe05bf8a1"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraPan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""6daf7aa4-38da-415e-86c2-769967957666"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraPan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""bc8c8132-ae57-49fc-85e0-62be55c6d92b"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""8ebf09c0-ba31-47b9-ad7a-69ec3a516659"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""b356f57a-1bc1-4ce6-99c2-5684e039c3d2"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""52be15d4-927b-45f4-a5cd-572a1e8aa993"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceBlock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""8022bf2e-c3db-4a23-bfad-74e41cc4965d"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RemoveBlock"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""4c5db633-77d1-4cce-9028-f9f055cd1c5e"",
                    ""path"": ""<Keyboard>/delete"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RemoveBlock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""b337c172-a510-423e-9409-953c2813468f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RemoveBlock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8778c576-3c31-47c9-a8d7-7d504919ef6b"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""FlyControls"",
            ""id"": ""b49b0dc7-d6b8-4085-be74-9ba5ba03320b"",
            ""actions"": [
                {
                    ""name"": ""FlyMove"",
                    ""type"": ""Value"",
                    ""id"": ""def1b046-7506-4bc8-a45e-9a85466acf90"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FlyModifier"",
                    ""type"": ""Button"",
                    ""id"": ""ba300004-48fb-46a0-88df-1ddce1c2492b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FlyLook"",
                    ""type"": ""Value"",
                    ""id"": ""29c82d3b-ffa0-41b6-b58e-a7d8345282ea"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e640b80b-f185-4f2a-b8b7-8ac87fa125c6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlyMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c6d633f1-11a4-48a7-afae-354a3f317cda"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlyMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ac7cd246-8f81-41b3-87fd-1134dc90b02b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlyMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9f5e29d0-1362-49f7-a8c7-e24fe6475e23"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlyMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0c6a6d4b-7a91-4f3c-b096-9513162eef38"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlyMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c9184b8b-9d15-42dc-91ce-98b2c35d196f"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlyModifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c56bed65-36a0-43de-977f-7910ff1a26dc"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlyLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Editor
        m_Editor = asset.FindActionMap("Editor", throwIfNotFound: true);
        m_Editor_CameraPan = m_Editor.FindAction("CameraPan", throwIfNotFound: true);
        m_Editor_CameraRotate = m_Editor.FindAction("CameraRotate", throwIfNotFound: true);
        m_Editor_CameraZoom = m_Editor.FindAction("CameraZoom", throwIfNotFound: true);
        m_Editor_PlaceBlock = m_Editor.FindAction("PlaceBlock", throwIfNotFound: true);
        m_Editor_RemoveBlock = m_Editor.FindAction("RemoveBlock", throwIfNotFound: true);
        // FlyControls
        m_FlyControls = asset.FindActionMap("FlyControls", throwIfNotFound: true);
        m_FlyControls_FlyMove = m_FlyControls.FindAction("FlyMove", throwIfNotFound: true);
        m_FlyControls_FlyModifier = m_FlyControls.FindAction("FlyModifier", throwIfNotFound: true);
        m_FlyControls_FlyLook = m_FlyControls.FindAction("FlyLook", throwIfNotFound: true);
    }

    ~@VoxelEditorInput()
    {
        UnityEngine.Debug.Assert(!m_Editor.enabled, "This will cause a leak and performance issues, VoxelEditorInput.Editor.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_FlyControls.enabled, "This will cause a leak and performance issues, VoxelEditorInput.FlyControls.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Editor
    private readonly InputActionMap m_Editor;
    private List<IEditorActions> m_EditorActionsCallbackInterfaces = new List<IEditorActions>();
    private readonly InputAction m_Editor_CameraPan;
    private readonly InputAction m_Editor_CameraRotate;
    private readonly InputAction m_Editor_CameraZoom;
    private readonly InputAction m_Editor_PlaceBlock;
    private readonly InputAction m_Editor_RemoveBlock;
    public struct EditorActions
    {
        private @VoxelEditorInput m_Wrapper;
        public EditorActions(@VoxelEditorInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @CameraPan => m_Wrapper.m_Editor_CameraPan;
        public InputAction @CameraRotate => m_Wrapper.m_Editor_CameraRotate;
        public InputAction @CameraZoom => m_Wrapper.m_Editor_CameraZoom;
        public InputAction @PlaceBlock => m_Wrapper.m_Editor_PlaceBlock;
        public InputAction @RemoveBlock => m_Wrapper.m_Editor_RemoveBlock;
        public InputActionMap Get() { return m_Wrapper.m_Editor; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EditorActions set) { return set.Get(); }
        public void AddCallbacks(IEditorActions instance)
        {
            if (instance == null || m_Wrapper.m_EditorActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_EditorActionsCallbackInterfaces.Add(instance);
            @CameraPan.started += instance.OnCameraPan;
            @CameraPan.performed += instance.OnCameraPan;
            @CameraPan.canceled += instance.OnCameraPan;
            @CameraRotate.started += instance.OnCameraRotate;
            @CameraRotate.performed += instance.OnCameraRotate;
            @CameraRotate.canceled += instance.OnCameraRotate;
            @CameraZoom.started += instance.OnCameraZoom;
            @CameraZoom.performed += instance.OnCameraZoom;
            @CameraZoom.canceled += instance.OnCameraZoom;
            @PlaceBlock.started += instance.OnPlaceBlock;
            @PlaceBlock.performed += instance.OnPlaceBlock;
            @PlaceBlock.canceled += instance.OnPlaceBlock;
            @RemoveBlock.started += instance.OnRemoveBlock;
            @RemoveBlock.performed += instance.OnRemoveBlock;
            @RemoveBlock.canceled += instance.OnRemoveBlock;
        }

        private void UnregisterCallbacks(IEditorActions instance)
        {
            @CameraPan.started -= instance.OnCameraPan;
            @CameraPan.performed -= instance.OnCameraPan;
            @CameraPan.canceled -= instance.OnCameraPan;
            @CameraRotate.started -= instance.OnCameraRotate;
            @CameraRotate.performed -= instance.OnCameraRotate;
            @CameraRotate.canceled -= instance.OnCameraRotate;
            @CameraZoom.started -= instance.OnCameraZoom;
            @CameraZoom.performed -= instance.OnCameraZoom;
            @CameraZoom.canceled -= instance.OnCameraZoom;
            @PlaceBlock.started -= instance.OnPlaceBlock;
            @PlaceBlock.performed -= instance.OnPlaceBlock;
            @PlaceBlock.canceled -= instance.OnPlaceBlock;
            @RemoveBlock.started -= instance.OnRemoveBlock;
            @RemoveBlock.performed -= instance.OnRemoveBlock;
            @RemoveBlock.canceled -= instance.OnRemoveBlock;
        }

        public void RemoveCallbacks(IEditorActions instance)
        {
            if (m_Wrapper.m_EditorActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IEditorActions instance)
        {
            foreach (var item in m_Wrapper.m_EditorActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_EditorActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public EditorActions @Editor => new EditorActions(this);

    // FlyControls
    private readonly InputActionMap m_FlyControls;
    private List<IFlyControlsActions> m_FlyControlsActionsCallbackInterfaces = new List<IFlyControlsActions>();
    private readonly InputAction m_FlyControls_FlyMove;
    private readonly InputAction m_FlyControls_FlyModifier;
    private readonly InputAction m_FlyControls_FlyLook;
    public struct FlyControlsActions
    {
        private @VoxelEditorInput m_Wrapper;
        public FlyControlsActions(@VoxelEditorInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @FlyMove => m_Wrapper.m_FlyControls_FlyMove;
        public InputAction @FlyModifier => m_Wrapper.m_FlyControls_FlyModifier;
        public InputAction @FlyLook => m_Wrapper.m_FlyControls_FlyLook;
        public InputActionMap Get() { return m_Wrapper.m_FlyControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FlyControlsActions set) { return set.Get(); }
        public void AddCallbacks(IFlyControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_FlyControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FlyControlsActionsCallbackInterfaces.Add(instance);
            @FlyMove.started += instance.OnFlyMove;
            @FlyMove.performed += instance.OnFlyMove;
            @FlyMove.canceled += instance.OnFlyMove;
            @FlyModifier.started += instance.OnFlyModifier;
            @FlyModifier.performed += instance.OnFlyModifier;
            @FlyModifier.canceled += instance.OnFlyModifier;
            @FlyLook.started += instance.OnFlyLook;
            @FlyLook.performed += instance.OnFlyLook;
            @FlyLook.canceled += instance.OnFlyLook;
        }

        private void UnregisterCallbacks(IFlyControlsActions instance)
        {
            @FlyMove.started -= instance.OnFlyMove;
            @FlyMove.performed -= instance.OnFlyMove;
            @FlyMove.canceled -= instance.OnFlyMove;
            @FlyModifier.started -= instance.OnFlyModifier;
            @FlyModifier.performed -= instance.OnFlyModifier;
            @FlyModifier.canceled -= instance.OnFlyModifier;
            @FlyLook.started -= instance.OnFlyLook;
            @FlyLook.performed -= instance.OnFlyLook;
            @FlyLook.canceled -= instance.OnFlyLook;
        }

        public void RemoveCallbacks(IFlyControlsActions instance)
        {
            if (m_Wrapper.m_FlyControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFlyControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_FlyControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FlyControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FlyControlsActions @FlyControls => new FlyControlsActions(this);
    public interface IEditorActions
    {
        void OnCameraPan(InputAction.CallbackContext context);
        void OnCameraRotate(InputAction.CallbackContext context);
        void OnCameraZoom(InputAction.CallbackContext context);
        void OnPlaceBlock(InputAction.CallbackContext context);
        void OnRemoveBlock(InputAction.CallbackContext context);
    }
    public interface IFlyControlsActions
    {
        void OnFlyMove(InputAction.CallbackContext context);
        void OnFlyModifier(InputAction.CallbackContext context);
        void OnFlyLook(InputAction.CallbackContext context);
    }
}
