[tool.poetry]
name = "buildscripts"
version = "0.1.0"
description = ""
authors = ["RyszardMinted <ryszard@proofofplay.gg>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
matplotlib = "^3.9.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
